### ISSUE TITLE
This kickstarter works with the radian R terminal

### ISSUE THREAD

**Issue by jasonpott** [jmbuhr/quarto-nvim-kickstarter#102]
In case others were interested to use the functionality of this kickstarter with the Radian terminal. This is easily accomplished by changing the following function in wk.register

Obviously you would need to have installed the [radian terminal](https://github.com/randy3k/radian).

```
    r = {
      function()
        vim.b["quarto_is_r_mode"] = true
        vim.cmd("split term://R")
      end,
      "new [R] terminal",
    },

```
to 

```
    r = {
      function()
        vim.b["quarto_is_r_mode"] = true
        vim.cmd("split term://radian")
      end,
      "new [R (radian)] terminal",
    },

```

![Screenshot 2024-04-10 at 10 25 01](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/43917006/3968f1a8-a449-4e14-81d5-01c1f58e255b)

**Comment by jasonpott** [comment]
I spoke too soon.  I need to work out why radian splits code chunks when the R terminal does not.

**Comment by jmbuhr** [comment]
It might need a different pasting behavior of vim-slime

**Comment by py9mrg** [comment]
I guess it's similar to VS Code using radian - needs bracketed paste.

**Comment by FernandoFailla** [comment]
@jasonpott Did you found a work around for using radian ?

**Comment by jasonpott** [comment]
I didn't but Rnvim  has implemented this in the latest update to main.
