### ISSUE TITLE
Syntax highlighting in *.qmd files missing.

### ISSUE THREAD

**Issue by murek-m** [jmbuhr/quarto-nvim-kickstarter#110]
Getting the following errors after a clean install of nvim and kickstarter. 

macOS 14.4.1
iterm2

<img width="1920" alt="Screenshot 2024-04-30 at 10 04 02" src="https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/11369435/14d74d03-b447-40e1-acc1-6194a9cbbecb">

<img width="1920" alt="Screenshot 2024-04-30 at 10 04 14" src="https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/11369435/8807577e-e060-449a-9dcb-7dfb13773034">

**Comment by murek-m** [comment]
macOS 14.4.1
iterm2

Thanks.

**Comment by jmbuhr** [comment]
what errors?

**Comment by murek-m** [comment]
Please check the screenshots provided. Otherwise this is what I get when launching a *.qmd file.

Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: Error executing lua: ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for
 "*"..function <SNR>1_LoadFTPlugin[19]..script /Users/mm/.config/nvim/ftplugin/quarto.lua: Vim(runtime):E5113: Error while calling lua chunk: /Users/mm/.config/nvim/ftplugin/quarto.lua:62: bad argument #1 to 'ipairs' (table expected, got
userdata)
stack traceback:
        [C]: in function 'ipairs'
        /Users/mm/.config/nvim/ftplugin/quarto.lua:62: in function 'highlight_cells'
        /Users/mm/.config/nvim/ftplugin/quarto.lua:70: in main chunk
        [C]: in function 'nvim_cmd'
        ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10>
Press ENTER or type command to continue
