### ISSUE TITLE
misc.handlers related error with lsp.lua

### ISSUE THREAD

**Issue by jeffinrockey** [jmbuhr/quarto-nvim-kickstarter#123]
Hi,
The below error on lsp.lua is recurring during the initial setup further to cloning into .config/nvim folder (I am setting up as to work with Quarto). Could you please let me know what could be done to resolve this. Info and error below.
Jeffin

```
Nvim version
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```

```
OS version:
NAME="openSUSE Tumbleweed"
VERSION="20240805"
```

Error:

```
`Error detected while processing /home/jeffin/.config/nvim/init.lua:
Failed to load `plugins.lsp`

/home/jeffin/.config/nvim/lua/plugins/lsp.lua:2: loop or previous error loading module 'misc.handlers'

# stacktrace:
  - .config/nvim/lua/plugins/lsp.lua:2 _in_ **load**
  - .config/nvim/lua/config/lazy.lua:16
  - .config/nvim/init.lua:14
`
```

**Comment by jmbuhr** [comment]
I couldn't replicate that exact error, but I just merged some changes from my dev branch. Are you still seeing the error with the latest main?

**Comment by jeffinrockey** [comment]
Hi,
  Took clone just now.  The issue did not occur. Thank you.
  (I am closing this issue)
Jeffin
