### ISSUE TITLE
Ctrl-H (backspace) stuck (does not respond)

### ISSUE THREAD

**Issue by spring-haru** [jmbuhr/quarto-nvim-kickstarter#129]
I use `Ctrl-H` as `backspace` and commented out the following lines in `keymap.lua` 
```
nmap('<C-h>', '<C-W>h')    <-   line 36
nmap('<c-h>', '<c-w>h')    <-   line 138
```

The problem is that `Ctrl-H` is stuck (does not respond) in the telescope search window.

To reproduce:
- start nvim and open Settings.
- <c-b> to open `nvim-tree` and delete a (unnecessary) file
- go back to the right window
- `space f f` to open the Telescope file search window and type some letters
- press `Ctrl-H`

Apple M1 Max with macOS 14.6.1
nvim 0.10.0

**Comment by jmbuhr** [comment]
This repo exists to show how I use the plugins I write in combination and to keep up-to-date with other plugins. Unfortunately troubleshooting personal issue is out of scope for this.
