### ISSUE TITLE
Add Github Copilot to this configuration

### ISSUE THREAD

**Issue by coffm049** [jmbuhr/quarto-nvim-kickstarter#20]
Is there a straight forward way to add Github Copilot to this configuration? I've gotten it to work without installing this kickstarter as my nvim configuration. 

I'm using Linux and what I've tried is 
git clone https://github.com/github/copilot.vim \
   ~/.config/nvim/pack/github/start/copilot.vim

But then when calling :Copilot setup from within nvim, Copilot isn't found.

**Comment by jmbuhr** [comment]
You can certainly add this plugin, just like you add any other plugin with lazy.nvim.

I personally prefer the version of copilot that gets integrated into the existing completion plugin:
https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/c4bb018ef59a46d73b0561dc0f5dee7db6255158/lua/plugins/quarto.lua#L368

**Comment by coffm049** [comment]
Wow that is incredible. Thank you for pointing that out.
