### ISSUE TITLE
Question: is there a way to get a conda environment working in the Python terminal?

### ISSUE THREAD

**Issue by thadryanjs** [jmbuhr/quarto-nvim-kickstarter#28]
Hello! Thanks for the work on this.

I am attempting to get the Python terminal to use a conda environment. I've tried adding this to the global config:

```lua
vim.g.python3 = '/home/thadryan/anaconda3/envs/binf1/bin/python'
```
I also tried through pyright in the config after reading [this](https://github.com/microsoft/pyright/blob/main/docs/settings.md):

```lua
      lspconfig.pyright.setup {
        on_attach = on_attach,
        capabilities = capabilities,
        flags = lsp_flags,
        settings = {
          python = {
            analysis = {
              autoSearchPaths = false, -- <----
              useLibraryCodeForTypes = true,
              diagnosticMode = 'openFilesOnly',
            },
            pythonPath = '/home/thadryan/anaconda3/envs/binf1/bin/python', -- <----
          },
        },
        root_dir = function(fname)
          return util.root_pattern(".git", "setup.py", "setup.cfg", "pyproject.toml", "requirements.txt")(fname) or
              util.path.dirname(fname)
        end
      }
```
...and [this](https://stackoverflow.com/questions/65847159/how-to-set-python-interpreter-in-neovim-for-python-language-server-depending-on).

I noticed that if I start nvim from a conda env then IPython honors it but the base python shell doesn't. Normally would just use IPython but haven't gotten that working yet due to an external thing.

If you could point me in the right direction that would be great.

Thanks:
    Thad

**Comment by jmbuhr** [comment]
Since you typically start vim from the terminal it should inherit whatever shell environment you currently have, including the `PATH` on which `python` is found. Try `which -a python` in your terminal to see which one is found first. Sometimes this can be out of date, in which case you may try `hash -r` to rehash the PATH.
The `pythonPath` shouldn't do anything, as the link you posed mentioned that this setting is deprecated. 

If all else fails you can also try a different way of using environments such as the python-builtin `venv` module.

**Comment by thadryanjs** [comment]
Thanks for the reply.

Trying this:

```bash
conda activate binf1
```

```bash
~:) which -a python
/home/thadryan/anaconda3/envs/binf1/bin/python
/home/thadryan/anaconda3/bin/python
```

(Also tried with the hash)

```bash
nvim
```

In nvim:

```bash
:checkhealth provider
```

Gives:

```bash
Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3.10 in the environment.
- Executable: /home/thadryan/anaconda3/bin/python3.10
- Python version: 3.10.10
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV
```

Opening Python terminal gives:

```bash
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
```

Where it would say conda instead of main, and no libraries from the env are usable.

Setting the `python3_host_prog` and `VIRTUAL_ENV` to the conda path gives a good `:checkhealth provider`:

gives:

```
    8 Python 3 provider (optional)
    9 - Using: g:python3_host_prog = "/home/thadryan/anaconda3/envs/binf1/bin/python"
   10 - Executable: /home/thadryan/anaconda3/envs/binf1/bin/python
   11 - Python version: 3.11.3
   12 - pynvim version: 0.4.3
   13 - OK Latest pynvim is installed.
   14 
   15 Python virtualenv
   16 - WARNING $VIRTUAL_ENV is set to: /home/thadryan/anaconda3/envs/binf1/bin/python
   17   But no Python executables found in the virtualenv /bin directory.
   18   So invoking Python may lead to unexpected results.
```

Stating I should be good for the main Python but doesn't fix it. I also thought starting the env then running nvim should fix it but it still defaults to system Python. This happens for me on Arch and VanillaOS. As mentioned, IPython honors the conda though so I'll see if I can get that working as conda is a dealbreaker for me right now.

Thanks!
----Thad

**Comment by jmbuhr** [comment]
Interesting, for me `<space>cp` opens the python in the conda environment that was started before opening nvim.
What happens if you open a bash terminal from inside nvim first (`<space>cn`) and then start python from there? (And also experiment with `which`)

**Comment by thadryanjs** [comment]
Good idea! When I open it that way, it activates my base conda environment (not the one I'm in). Progress! When I use it that way I get the treesitter error that's already know but it's something to go on. 

I'll let you know if I find anything interesting when I go back to it.

**Comment by jmbuhr** [comment]
what treesitter error?

**Comment by thadryanjs** [comment]
Apologies, I got an error that looked a little like [this](https://github.com/quarto-dev/quarto-nvim/issues/41) but it's not the same. I'm running someone else's code that work in works in ipynb but gives a bunch of indentation errors when I put it into quarto. I'll have to mess around with it again when I have time. This is a solid workaround for the conda stuff though so thanks!

**Comment by jmbuhr** [comment]
Part of the reason ipython has this paste magic is that pasting multiline blocks into repls can be tricky depending on the repl. I never had a problem with it in R for example, but R doesn't care about whitespace like python does, so the pure python repl can be tricky. Another workaround for you would be to use `tmux` which handles multiline pasting into any panel nicely, instead of the integrated nvim terminal.
https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/96472327715fb1f36f336e3753e6dd6362fba3bb/lua/plugins/quarto.lua#L541-L544

This is what the workflow would look like: https://youtu.be/CS0rpe2izI4?t=939

**Comment by thadryanjs** [comment]
Yeah R was smooth from the get-go. Thank you very much I will look into this!

**Comment by thadryanjs** [comment]
Hello!

To come full circle here and leave this for posterity:

tmux doesn't resolve it (but it was good to learn and I used it now, so cheers!). I've confirmed what it is, and I think it's just a Python thing - you can't have a blank line without causing evaluation, and you must have one if you indent:

For example:
```{python}
# works
class Foo:
    def __init__(self):
        print("Foo online")

f = Foo() 
```

This works because there is an indented structure then a space before anything else. This, however, does not:

```{python}
# does not work - sees bar as improperly indentented part of Foo
class Foo:
    def __init__(self):
        print("Foo online")
bar = Foo()
```

It interprets `bar` as part of `Foo` (or `__init__`) that isn't indented correctly because there is no space.

```{python}
# also doesn't work 
class Foo:

    def __init__(self):
        print("Foo online")

bar = Foo()
```

This one also doesn't work, as it thinks `class Foo:` is floating with no definition. This is really particular because it dictates how you style your class code (can't have a line between methods).

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/31735051/718ccaf2-3e37-417b-afbf-65ef67a9dd03)


All that is to say, this is probably a Python thing not a nvim-quarto thing, as you suspected.

Thanks for working on this!
