### ISSUE TITLE
r-languageserver installation

### ISSUE THREAD

**Issue by bdavc** [jmbuhr/quarto-nvim-kickstarter#29]
Hello,

I wanted to try your kickstart configuration, as I'm just starting with Neovim, everything seems fine, but i can't make it install the r-languageserver.

Do you have any idea of the cause of the problem?

Thanks.

![nvim](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/128183681/94b27495-f284-48f3-b196-eee501f67585)

**Comment by jmbuhr** [comment]
Try `:MasonLog` to check the logfile of Mason, the language server installer  (https://github.com/williamboman/mason.nvim#commands)

**Comment by bdavc** [comment]
I have this in the log :
![Log](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/128183681/4d2c6ee9-7dce-4d35-88eb-00435ccab15a)

**Comment by jmbuhr** [comment]
Looks like some problem with powershell. What happens if you run this in a regular cmd shell? You might have to follow the breadcrumb trail into mason's init.lua as mentioned in the logfile. Or disable installation of the R language server in the config and install it manually as the R package.

**Comment by bdavc** [comment]
The regular cmd shell does the same thing, here is what it says :
![Mason1](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/128183681/f697f305-f547-4e17-ba76-1e701e67b948)
![Mason2](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/128183681/402f5c35-3e18-402c-b84d-32b416dd6e27)

**Comment by jmbuhr** [comment]
do you have R installed and available on the PATH?

**Comment by bdavc** [comment]
Was it ! The path for R wasn't set in the right folder, everything's good now.
Thanks.
