### ISSUE TITLE
Feature suggestion: automated local .bib file generation

### ISSUE THREAD

**Issue by H-Mateus** [jmbuhr/quarto-nvim-kickstarter#49]
RStudio has the ability to search one's entire zotero library when inserting references, and then generate a local `references.bib` file that only contains the subset used in the quarto doc, which is super handy.

I'm wondering if it'd be possible to add similar functionality to the kickstarter?

I had hacky setups in emacs where I'd export the whole zotero library as a `masterlib.bib` file from zotero and then use that to source reference key completion.
I then had an even more hacky bash script to generate the locally used bib file:

```
## loop to extract keys used in thesis
  for i in $(cat bib/used_bib_keys.bib)
  do
    sed -n "/$i/,/^$/p" ~/Documents/masterLib.bib >> bib/thesis.bib
  done


## use bibtex-tidy (npm program) to clean .bib file
bibtex-tidy --omit=file --curly --numeric --space=2 --tab --align=13 --duplicates=key --no-remove-dupe-fields --backup bib/thesis.bib
```

I'm sure there are much more elegant solutions to this, but what do you think?

**Comment by jmbuhr** [comment]
There is one indeed! The Zotero extension better-bib-tex has an option to keep the exported `.bib` file up to date automatically: https://github.com/retorquere/zotero-better-bibtex

Though in this version the process starts in Zotero, which makes sense for most applications (e.g. that's where I am after adding or reading a paper anyways, so it will sync to the bib file automatically), but it does not go the ather way.

If you really want to go the "global bib file with all citations"-route, I would be happy about a PR to https://github.com/jmbuhr/cmp-pandoc-references.
You'd have to add the discovery of a configured global bib file to https://github.com/jmbuhr/cmp-pandoc-references/blob/master/lua/cmp-pandoc-references/references.lua and then augment the complete functionality to add the completed entry to a local bib file: https://github.com/jmbuhr/cmp-pandoc-references/blob/master/lua/cmp-pandoc-references/init.lua#L17

That would certainly be a fun project to get into neovim/quarto lua development. If you make it work I can help with making it configurable.

**Comment by jmbuhr** [comment]
Sidenote: I just clicked on your personal website and absolutely love the interactive network visualization on your home page.
As another aside, you set both the witdth and the height on your profile picture on the about page, so you look more squished than you probably do in real life ;)

**Comment by H-Mateus** [comment]
Thanks!

It seems tantalisingly doable, even with my near total ignorance of lua, so I'll see if I can have a play and figure it out :+1: 

And thanks on the website, I can't recall from where, but I copied most of the java script for the home page visual, so I can't take too much credit for it!
I made it with blogdown and keep meaning to sort out the image, but have yet to get around to it :sweat_smile:

**Comment by H-Mateus** [comment]
As a quick update, I got the global bib file working pretty easily (https://github.com/H-Mateus/cmp-pandoc-references/commit/550b0fd130e9c6368c1e51dc1022491abf0685dc), but generating a local .bib file with the references used is harder :sweat_smile: 

I'll keep trying though!

**Comment by jmbuhr** [comment]
I also wonder if one can interact with zotero directly through an API? Maybe we can see how rstudio does it in their code.

**Comment by H-Mateus** [comment]
That's a good point, I hadn't thought of that, I'll have a look-see :+1:

**Comment by jmbuhr** [comment]
Oh, looks like it already exists partially! https://github.com/tiagovla/zotex.nvim
I haven't tested it, but it looks promising.

**Comment by H-Mateus** [comment]
As an update, I'm still fighting away at this!

That api plugin scared me away, but I finally managed to get [a lua script](https://github.com/H-Mateus/cmp-pandoc-references/blob/master/lua/cmp-pandoc-references/update-local-bib-standalone.lua) that takes a file to parse, a global bib file and a local bib file to create/update, and it seems to do the job

In the end I just wrote a working bash script and thought I could just add a function to call that in neovim, but then I tried asking chatgpt to rewrite it in lua on a whim, and to my surprise it got it mostly right :shrug:
With a bit to tweaking to exclude "@fig-" and "@tbl-" keys it seems to do what I was after

I'm just trying to figure out how to actually incorporate it into the plugin now 😅 

I figure I'll try and get it as a function one could call when desired before I hurt my head trying to incorporate it into the autocompletion...

**Comment by jmbuhr** [comment]
Translating code between languages is also something I found LLMs helpful for, less chance of them making up stuff.

If you want to quickly test it out in your neovim config, you can turn the script into a module and expose the main function. Then e.g. use `vim.keymap.set` to map the function to a key and you can iterate quickly.

e.g.
```lua
M = {}

-- helpers

M.do_stuff = function()
end

return M

```

In nvim config:

```lua
mymodule = require'mymodule'
vim.keymap.set('n', '<leader>xt', mymodule.do_stuff, {})
```

**Comment by H-Mateus** [comment]
I think the simplest version of this is pretty much there now!

I've [set it to](https://github.com/H-Mateus/cmp-pandoc-references/blob/master/lua/cmp-pandoc-references/init.lua#L30-L31) update the local .bib automatically after completion if `vim.g.global_bib_file` is set.
The completions will only be sourced from the global bib file if the same variable is set too, so if it's nil then the plugin should behave the as it did

It currently reads in the current buffer as a file, so it only inserts entries present whenever the file was last written from my testing.
I added a [command](https://github.com/H-Mateus/cmp-pandoc-references/blob/master/lua/cmp-pandoc-references/init.lua#L6) one could just call, so I might just make a key binding for that in my config and use that personally 🤷 

It'd probably be more elegant to parse the current buffer contents instead, but I've had enough of thinking for today 😅

I can put a PR together if you fancy having a play with it?

**Comment by H-Mateus** [comment]
Have you had a chance to look at the PR?

I'd be interested to hear your thoughts on my attempt 😁

**Comment by jasonpott** [comment]
I wondered if you had seen the telescope extension for this purpose? https://github.com/nvim-telescope/telescope-bibtex.nvim

**Comment by jmbuhr** [comment]
the telescope extension doesn't add anything that the completion source doesn't do already. What would be exciting is an integration with zotero

**Comment by jmbuhr** [comment]
Solved with https://github.com/jmbuhr/telescope-zotero.nvim
Demo: https://www.youtube.com/watch?v=_o5SkTW67do
