### ISSUE TITLE
Feature Request: Auto-Completion for Sub-Variable-Names

### ISSUE THREAD

**Issue by FriederRodewald** [jmbuhr/quarto-nvim-kickstarter#57]
First of, thank you so much for this repo and your work on otter.nvim and the quarto-nvim package; it really helped me to to get neovim setup for coding in R and it is so much fun now :otter: 
I was wondering whether it would be possible to get auto-completion for sub-variable names, e.g., for variables of a data-frame (in R). For example, when using the base-r `mtcars` example, I would directly get suggestions for variable names after the $-sign (`mtcars$...`). Ideally, this would also work in 'piped environments' while using tidyverse packages, like in RStudio. Maybe there is already a solution, but I was so far not able to find it.

**Comment by FriederRodewald** [comment]
Thank you, your last suggestion sounds quite cool and would make writing R  :)
I will try a solution with nvim-r in the next weeks and see how it goes.

**Comment by jmbuhr** [comment]
Update: Nvim-R has now moved to https://github.com/R-nvim/R.nvim and implemented many cool new things! I'm excited to try it out myself, but haven't found the time to far. But I believe it does exactly what you need.

**Comment by FriederRodewald** [comment]
Perfect, thanks - I'll have a look :)
