### ISSUE TITLE
Error when opening quarto-nvim-kickstarter

### ISSUE THREAD

**Issue by liston** [jmbuhr/quarto-nvim-kickstarter#63]
Hi,
I am getting a similar error message to one that was reported earlier in this thread. After I cloned the repo and opened Neovim, I get 'Failed to run 'config' for image.nvim
nvim/lua/plugins/ui.lua:234: attempt to call field 'system' (a nil value)

# stacktrace:
nvim/lua/plugins/ui.lua:234 _in_ **config**
nvim/lua/config/lazy.lua:16
nvim/init.lua:2

I removed the files in .local /nvim share and state and cloned again, but the same message still came up.

I hope you can help.

**Comment by jmbuhr** [comment]
what version of neovim are you on?

**Comment by liston** [comment]
I tried  0.9.0 and  0.9.4 both gave the same response.

**Comment by jmbuhr** [comment]
Ah, yes. Looks like, ironically, the function I'm using to check for dependencies for a new plugin via a shell command is only available in nvim 0.10, so I'm going to have to check for that as well.

**Comment by jmbuhr** [comment]
Should be fixed now :)

**Comment by liston** [comment]
Thanks, No errors now.
