### ISSUE TITLE
Bug: /usr/share/nvim/runtime/lua/vim/_system.lua:241: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ReedMerrill** [jmbuhr/quarto-nvim-kickstarter#65]
At startup I get the following error. I'm not sure how to resolve this but it seems like an issue with lazy.nvim because that's the only location on my system with an images.nvim file. So far I haven't noticed any actual functionality issues.

```
Failed to run `config` for image.nvim

/usr/share/nvim/runtime/lua/vim/_system.lua:241: ENOENT: no such file or directory

# stacktrace:
  - /usr/share/nvim/runtime/lua/vim/_system.lua:241 _in_ **spawn**
  - /usr/share/nvim/runtime/lua/vim/_system.lua:332 _in_ **system**
  - .config/nvim/lua/plugins/ui.lua:236 _in_ **shell**
  - .config/nvim/lua/plugins/ui.lua:257 _in_ **config**
  - .config/nvim/lua/config/lazy.lua:16
  - .config/nvim/init.lua:2
```

**Comment by jmbuhr** [comment]
what version of nvim are you on? I have a ceck in there to only use the `vim.system` function in a neovim version that already has this, but maybe I got the exact version it got added wrong.

**Comment by jmbuhr** [comment]
Or maybe your nvim runtime path doesn't match the  actual neovim version on your system
