### ISSUE TITLE
Setup fails for new installation of nvim and quarto on MacOS

### ISSUE THREAD

**Issue by jkroes** [jmbuhr/quarto-nvim-kickstarter#69]
![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/18478163/e8688afb-4b9b-4919-909c-0f850a958571)

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/18478163/067090fa-7eea-4a64-8b44-6390c535e8a4)

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/18478163/b67d619c-ecf3-4e7e-8bde-1cf59d7236ad)

**Comment by jmbuhr** [comment]
Can you check if this fixes it? Looks like you have some version of the `kitty` terminal installed, but I can't parse the output of `kitty --version` into a version number to check if I can enable the `image.nvim` plugin.

Is this the case and if yes, what is the output of said command on your machine?
