### ISSUE TITLE
Unknown conflict triggers repeated command request when in insert mode

### ISSUE THREAD

**Issue by py9mrg** [jmbuhr/quarto-nvim-kickstarter#76]
Hello,

This is a bit of a weird issue to describe, but I am having a problem where - when I enter insert mode - it keeps reverting to requesting a command which means characters can be missed when typing. I'll try and elaborate visually, let's say I open an .R file (same problem with .qmd), then I start with this view:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/787c2b96-faad-4bb6-9f95-7da0aaccfc87)

When I press `i`, a command is requested unexpectedly:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/7a53dfe8-8a8a-4eab-be17-16aec1c4761b)

If I press enter I go into insert mode:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/a293a784-f775-4162-91c3-635547ab44a0)

But when I press a key to type, it switches back to requesting a command:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/f4f18581-1e26-4871-bf32-4af50f3f5cac)

I can ignore this and press another key:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/37c808c6-99cb-4d43-8611-4d41ec961d4a)

But if I carry on typing it will sometimes cause characters to be missed as it switches back and forth between insert mode and requesting a command. For example, I continued typing alphabetically but the `g` got missed:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/c3e49d8b-dbc4-4808-9fba-acef6a537d3f)

For this issue I am using Wezterm on Fedora ~~40~~ 39 - but I get the same problem using Gnome Terminal, and also using Wezterm on Windows - so I don't think this is OS or terminal specific. 

Fixes I've tried so far:

* I did a full neovim reset (removing `~/.local/share/nvim`, `~/.local/state/nvim`, and `~/.cache/nvim`). 
* I tried various previous commits of the quarto-nvim-kickstarter and that doesn't fix it either.

Any ideas how I can fix this please?

Edit: Fedora 40 -> 39, getting a bit ahead of myself on the Fedora release cycle!

**Comment by jmbuhr** [comment]
Can you check `:message`s after this happens?

**Comment by jmbuhr** [comment]
maybe one of mine or some other plugin has a leftover debugging print statement that executes on typig and waits for confirmation

**Comment by py9mrg** [comment]
Crikey, that was a quick reply! Here is what I get:

```
RPC[Error] code_name = unknown, code = 1000, message = "Not authenticated: NotSi
gnedIn"
RPC[Error] code_name = unknown, code = 1000, message = "Not authenticated: NotSi
gnedIn"
```

**Comment by jmbuhr** [comment]
Lucky timing ;)
I believe that is copilot (https://github.com/zbirenbaum/copilot.lua).

You can disable it in the config or configure or disable it via `: Copilot ...`

**Comment by py9mrg** [comment]
Perfect - that fixed it, thank you so much!
