### ISSUE TITLE
error installing kickstarter on linux

### ISSUE THREAD

**Issue by alejandrohagan** [jmbuhr/quarto-nvim-kickstarter#77]
hi!

After installing the kickstarter, I got the below error.

I am using pop0S as my linux distribution.

```
Error detected while processing /home/hagan/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:570: Not a valid option name: winbar
stack traceback:
        [C]: in function 'assert'
        vim/_meta.lua:570: in function 'make_option'
        vim/_meta.lua:638: in function '__newindex'
        /home/hagan/.config/nvim/lua/config/global.lua:72: in main chunk
        [C]: in function 'require'
        /home/hagan/.config/nvim/init.lua:1: in main chunk
```

**Comment by jmbuhr** [comment]
the winbar option was introduced to nvim in v0.8.4. I recommend to install the latest stable version (0.9) via their appimage from the GitHub release. Though I believe the deb package was also recently updated to 0.9 in the debian repositories, so maybe pop-os will also get this already if you apt update and upgrade.
