### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by egolep** [jmbuhr/quarto-nvim-kickstarter#8]
Maybe it is a stupid question, but I don't understand which (if any) package manager is used for this configuration.
I'm trying to merge this configuration with mine since simply installing the `quarto.nvim` plugin with `otter.nvim` and following the given configuration I get an error.
I tried this configuration and everything works smoothly, but I don't want to lose my entire configuration. If this configuration is build without a package manager, could I add my own preferred package manager and re-install the other plugins I need?

**Comment by jmbuhr** [comment]
The package manager is lazy.nvim, which is fairly new but gained traction really fast. I show you around the configuration and some of the features in this playlist: https://youtube.com/playlist?list=PLabWm-zCaD1axcMGvf7wFxJz8FZmyHSJ7

**Comment by egolep** [comment]
How I'm sorry, this was indeed a stupid question. Never heard of `lazy.nvim`, I'll check it out.
Thanks for the quick reply!

**Comment by egolep** [comment]
Sorry to bother again, complete different topic but I don't want  to clutter the issues section. I keep getting alerts that malicious plugins can harm my computer and then I have to manually select if I want to load the specific plugin or not. Is this related to the config or there is some of the plugins used that spawns this message? I would like to simply load the plugins by default without this alert.

**Comment by jmbuhr** [comment]
No worries! I am assuming you also figured out that the warning you found comes from the lua language server, because we are loading the quarto, pandoc and neovim lua files so that you get code completion for these things as well.
