### ISSUE TITLE
error with langagueserver / installation

### ISSUE THREAD

**Issue by alejandrohagan** [jmbuhr/quarto-nvim-kickstarter#80]
hi -- 

sorry for the back and forth on the issues -- I've tried everything including clean purging and clean installs of nvim. 

I can  mostly get the quarto to work however it appears few of the language servers are working.

Below are  error messages that I cant when I try to start up nvim

Upon startup of nvim
```
Error detected while processing /home/hagan/.config/nvim/init.lua:
[Copilot] copilot_node_command(node) is not executable
[mason-lspconfig.nvim] installing cssls
[mason-lspconfig.nvim] installing html
[mason-lspconfig.nvim] installing emmet_language_server
[mason-lspconfig.nvim] installing yamlls
[mason-lspconfig.nvim] installing dotls
[mason-lspconfig.nvim] installing pyright
[mason-lspconfig.nvim] installing bashls
```

upon opening up settings

```
:e $MYVIMRC | :cd %:p:h                                                                                                                                                                       
/home/hagan/.config/nvim
```
During the installation phase -- I get the following:

Failed to run `config` for headlines.nvim
```
...t/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'markdown' language, see :help treesitter-parsers

# stacktrace:
  - /tmp/.mount_nvim28iQYt/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:93 _in_ **add**
  - /tmp/.mount_nvim28iQYt/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252 _in_ **parse**
  - .config/nvim/lua/plugins/ui.lua:212 _in_ **config**
  - .config/nvim/lua/config/lazy.lua:16
  - .config/nvim/init.lua:2
Press ENTER or type command to continue
```

Below is sreenshot of what I see upon start up once I move past the initial error message

![Screenshot from 2023-12-29 11-22-48](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/87534364/e5c29c32-e54e-49af-ab90-e29192366820)

**Comment by jmbuhr** [comment]
Did you check the logs like the screenshot suggests?

**Comment by alejandrohagan** [comment]
Hi,

Yes, it appears the issue is due npm not being executable. This error combined with error up above (`[Copilot] copilot_node_command(node) is not executable`) makes me think that whatever needs node.js isn't working.  

```
[ERROR Fri 29 Dec 2023 07:28:43 PM CST] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=bash-language-server) error=spawn: npm failed with exit code - and signal -. npm is not executable
```

**Comment by jmbuhr** [comment]
Yes, you need npm for Mason to install the language servers, or install them manually.

**Comment by alejandrohagan** [comment]
thank you! okay I install node js and that resolved many issues. I think the last issue I am facing are related to the treesitter. It appears it is missing some configurations and it is not loading (thus I think the language server isn't work either).
Not only is tree sitter not loading upon start up (which I can address by manually loading it) but after I load it and insepect the quarto.lua file I see many warnings (one example below) -- could this be why the language server support isn't working for R or Python?

Is this something I need to work with treesitter to figure out?

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/87534364/fc628ac4-6163-4da9-8644-ce958a3e3118)

**Comment by alejandrohagan** [comment]
okay -- I was able to figure it out -- I can't figure out why my tree sitter doesn't load at start up but once it is loaded I am able to replicate your tutorials on your tube series. 

Thanks for the work and correspondence!
