### ISSUE TITLE
lspconfig not attaching to quarto files & code blocks not highlighted

### ISSUE THREAD

**Issue by MarcoCamilo** [jmbuhr/quarto-nvim-kickstarter#82]
I'm trying to incorporate elements from the quarto-nvim-kickstarter to [my config](https://github.com/MarcoCamilo/nvim), but I can't seem to find in the quarto.lua file in the kickstarter what makes the lsp for python attach to qmd files. 

Currently, I open a qmd file and neither have autocompletion for Python and nor autoindentation for Python code (even within code chunks).

Any help I'll gladly appreciate, as trying to piece and modularize the plugins stated in the kickstarter into my own config. :)

**Comment by jmbuhr** [comment]
You need to call `quarto-nvim`s setup function (see https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/lua/plugins/quarto.lua), configure a language server for python (search for lspconfig.pyright in the file) and configure the `otter.nvim` source for `nvim-cmp`.

**Comment by MarcoCamilo** [comment]
Got, I’ll check that and get back on it. 

Regarding treesitter, it’s been working with everything else so far, what in particular do I have to make sure is modified for quarto?

**Comment by jmbuhr** [comment]
No modification necessary, just the usual setup and installed parsers. Quarto uses the regular markdown parser for now.

Also, note that more detailed formatting depends on the language server. There is very basic re-indentation with the usual vim command `=` you can do that uses treesitter, like `=ip` (reindent inside paragraph) or in this config also `=ic` (inside code chunk), but e.g. pyright does not come with a formatting lsp request while the R language server does.

**Comment by jmbuhr** [comment]
For python you could create a custom shortcut to call e.g. `vic:!black -q -` to filter the current code chunk through the black formatter via stdin.
